# Generated by Django 5.2.2 on 2025-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_alter_design_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to='designs/', verbose_name='Imagem Principal'),
        ),
    ]
