# Generated by Django 5.2.2 on 2025-06-07 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo de Produto')),
                ('slug', models.SlugField(help_text='Versão do nome otimizada para URLs.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Produto',
                'verbose_name_plural': 'Tipos de Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Variação')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='products/icons/', verbose_name='Ícone Visual')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variations', to='products.producttype', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Variação de Produto',
                'verbose_name_plural': 'Variações de Produtos',
                'unique_together': {('product_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.productvariation', verbose_name='Variação de Produto')),
            ],
            options={
                'verbose_name': 'Faixa de Preço',
                'verbose_name_plural': 'Faixas de Preço',
                'ordering': ['quantity'],
                'unique_together': {('product_variation', 'quantity')},
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Característica')),
                ('value', models.CharField(max_length=255, verbose_name='Valor da Característica')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.productvariation', verbose_name='Variação de Produto')),
            ],
            options={
                'verbose_name': 'Especificação',
                'verbose_name_plural': 'Especificações',
                'unique_together': {('product_variation', 'name')},
            },
        ),
    ]
