# Generated by Django 5.2.2 on 2025-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='icon',
            field=models.CharField(blank=True, help_text="Ex: 'bi-rulers' ou 'bi-palette'. Veja os nomes em bootstrap-icons.", max_length=50, verbose_name='Classe do Ícone (Bootstrap Icons)'),
        ),
    ]
