# Generated by Django 5.2.2 on 2025-06-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productvariation_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='design_creation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor cobrado para criar a arte para este tipo de produto. Deixe 0 se não houver taxa.', max_digits=10, verbose_name='Taxa de Criação de Arte'),
        ),
    ]
