# Generated by Django 5.2.2 on 2025-06-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_producttype_design_creation_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem que aparecerá na galeria de produtos.', null=True, upload_to='product_types/', verbose_name='Imagem representativa do produto'),
        ),
    ]
