# Generated by Django 5.2.2 on 2025-06-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_image_alter_producttype_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem que aparecerá na galeria de produtos.', null=True, upload_to='product_types/', verbose_name='Imagem representativa do produto'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/icons/', verbose_name='Ícone Visual'),
        ),
    ]
